[package]
name = "rdslink"
version = "0.4.0"
edition = "2024"

[dependencies]
aws-config = "1.8.8"
aws-sdk-ec2 = "1.175.1"
aws-sdk-rds = "1.112.1"
aws-sdk-sts = "1.86.0"
clap = { version = "4.5.49", features = ["derive"] }
inquire = "0.9.1"
tokio = { version = "1.48.0", features = ["full"] }
