[package]
name = "rdslink"
version = "0.4.0"
edition = "2024"

[dependencies]
aws-config = "1.8.10"
aws-sdk-ec2 = "1.178.0"
aws-sdk-rds = "1.113.0"
aws-sdk-sts = "1.86.0"
clap = { version = "4.5.51", features = ["derive"] }
inquire = "0.9.1"
tokio = { version = "1.48.0", features = ["full"] }
