[package]
name = "rdslink"
version = "0.4.1"
edition = "2024"

[dependencies]
aws-config = "1.8.12"
aws-sdk-ec2 = "1.200.0"
aws-sdk-rds = "1.123.0"
aws-sdk-sts = "1.96.0"
clap = { version = "4.5.54", features = ["derive"] }
inquire = "0.9.2"
tokio = { version = "1.49.0", features = ["full"] }
